### ISSUE TITLE
[Porto Alegre] PHP Conference Brasil

### ISSUE THREAD

**Issue by rhcarlosweb** [backend-br/eventos#17]
**Título**: PHP Conference Brasil
  
**Data**: 6 a 8 de Dezembro 2018

**Local**: Faculdade SENAC - Porto Alegre (RS)

**Descrição (breve)**:
O Principal evento de PHP da América Latina

**Logotipo do evento**: 
<img src="https://phpconference.com.br/wp-content/uploads/2018/03/PHP-Conference-Brasil-Logo-W-S-100px.png">

**Valor**: 
- Silver: Inclui todas as palestras
- Gold: Inclui todas as palestras e um Curso Mão-na-Massa de 8 horas que será escolhido com antecedência e oportunamente a partir do LOTE 1.

~~Lote - 1 Até 14 de Setembro  [Encerrado]~~

**Lote 2 - Até 30 de Novembro**
**Clientes**:
Silver: R$199,00
Gold: R$349,00 

**Não-Clientes**:
Silver: R$249,00
Gold: R$399,00 

**Lote 3 - Até 4 de Dezembro**
**Clientes**:
Silver: R$249,00
Gold: R$399,00 

**Não-Clientes**:
Silver: R$299,00
Gold: R$449,00 

**Mais informações**: 
https://phpconference.com.br

**Transmissão ao vivo**:
Não informado

**O conteúdo será gravado**:
Não informado

**Comment by gustavofreze** [comment]
Evento já realizado.
