### ISSUE TITLE
[São Paulo] BackEnd BR #11  (Evento extra)

### ISSUE THREAD

**Issue by onhernandes** [backend-br/eventos#23]
<p>• O que vamos fazer<br/>Dia 23/05 às 19h00 teremos o primeiro meetup extra de 2019 na Movile!</p> <p>Seguimos o Código de Conduta do CodamosClub (<a href="https://www.codamos.club/codigo-de-conduta" class="linkified">https://www.codamos.club/codigo-de-conduta</a>)<br/>________<br/>Palestrantes:</p> <p>A confirmar<br/>________<br/>Quer palestrar ?</p> <p><a href="https://survey.binds.co/link/E0ePw7yMVdqXozneolkwVv4PTq2rV6vRrJKxG1J9Bjn8Nm2W/?loop=true&amp" class="linkified">https://survey.binds.co/link/E0ePw7yMVdqXozneolkwVv4PTq2rV6vRrJKxG1J9Bjn8Nm2W/?loop=true&amp</a>;<br/>________</p> <p>Apoio: Movile<br/>Linkedin --&gt; linkedin.com/company/movile<br/>Instagram --&gt; @movilelife<br/>Twitter --&gt; @movilebr<br/>Blog de tecnologia --&gt; movile.blog</p>

**Comment by wilton-alves** [comment]
Eu gostaria de participar!
Como eu faço pra me inscrever para assistir as palestras?
