### ISSUE TITLE
[São Paulo] BackEnd BR #13 - Edição JS

### ISSUE THREAD

**Issue by onhernandes** [backend-br/eventos#25]
<p>• O que vamos fazer<br/>Dia 10/09 às 19h00 teremos mais um meetup do BackEndBrasil, dessa vez focado em JavaScript!</p> <p>Seguimos o Código de Conduta do CodamosClub (<a href="https://www.codamos.club/codigo-de-conduta" class="linkified">https://www.codamos.club/codigo-de-conduta</a>)</p> <p>---</p> <p>PALESTRAS EM BREVE</p> <p>---</p> <p>Apoio: In Loco<br/>LinkedIn: <a href="https://www.linkedin.com/company/inlocoglobal/" class="linkified">https://www.linkedin.com/company/inlocoglobal/</a></p>

**Comment by gustavofreze** [comment]
Evento já realizado.
