### ISSUE TITLE
[Belo Horizonte] - Devops Day BH 2019

### ISSUE THREAD

**Issue by carolperezez** [backend-br/eventos#26]
Título: [Belo-Horizonte] Devops Day BH 2019

Data: 28/09/2019 08h - 18h

Local: PUC Minas - Campus Praça da Liberdade (Av. Brasil, 2023 - Funcionários, Belo Horizonte - MG)

Descrição: A Devopsdays é uma série mundial de conferências técnicas cobrindo tópicos de desenvolvimento de software, operações de infraestrutura de TI e a interseção entre eles. 
A maioria dos eventos devopsdays apresenta uma combinação de palestras organizadas e conteúdo de espaço aberto auto-organizado . Os tópicos geralmente incluem automação, teste, segurança e cultura organizacional.

Valor: 4º Lote - R$ 110,00. A startup de e-commerce Nuvemshop, uma das apoiadoras do evento, está realizando um concurso e levará um convidado para o evento! (Despesas com alimentação, transporte ou hospedagem não serão custeadas)
Caso você tenha interesse, é só acessar [https://lnkd.in/ersuNtg](url) e participar :)

Mais informações: [https://devopsdays.org/events/2019-belo-horizonte/program](url)

**Comment by gustavofreze** [comment]
Evento já realizado.
