### ISSUE TITLE
[Online] Engenharia de U4B no Brasil - UBER Tech Talks

### ISSUE THREAD

**Issue by Cami-recrut** [backend-br/eventos#27]
**Título**: Engenharia de U4B no Brasil - UBER Tech Talks.

**Descrição**: Estamos expandindo os times de tecnologia do Brasil, e uma das novas equipes é a de Uber For Business (U4B). Em nosso próximo meet-up, vocês poderão conhecer os Engineering Managers que vão nos contar sobre os desafios do time de U4B no Brasil, além de alguns cases técnicos.

**Data**: 14/12/2022 18:00h - 19:00h.

**Local**: Online.

**Valor**: Gratuito.

**Mais informações**: [Página do meetup](https://www.meetup.com/pt-BR/Uber-tech-talks-Sao-Paulo/events/282387434).

**Comment by gustavofreze** [comment]
Evento já realizado.
